---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressip-ipam-operator
rules:
  - apiGroups:
    - redhatcop.redhat.io
    resources:
    - egressipams
    - egressipams/finalizers
    - egressipams/status
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch    
  - apiGroups:
    - ""
    resources:
    - nodes
    - namespaces
    - secrets
    verbs:
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create  
    - patch
    - update    
  - apiGroups:
    - "network.openshift.io"
    resources:
    - netnamespaces
    - hostsubnets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
    - "config.openshift.io"
    resources:
    - infrastructures
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - "cloudcredential.openshift.io"
    resources:
    - credentialsrequests
    verbs:
      - get
      - list
      - watch
      - create
      - update              
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: egressip-ipam-operator
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - egressip-ipam-operator
  verbs:
  - "update"
